version: "3"

services:
  postgres_ignite:
    image: postgres
    container_name: postgres_ignite
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    restart: always
    links:
      - postgres_ignite
    depends_on:
      - postgres_ignite
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app


volumes:
  pgdata:
    driver: local